// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: circleoftrustmembers.proto

package circleoftrustmembers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CircleOfTrustMembersProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberIds []int64 `protobuf:"varint,1,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // list of user IDs
}

func (x *CircleOfTrustMembersProto) Reset() {
	*x = CircleOfTrustMembersProto{}
	mi := &file_circleoftrustmembers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircleOfTrustMembersProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircleOfTrustMembersProto) ProtoMessage() {}

func (x *CircleOfTrustMembersProto) ProtoReflect() protoreflect.Message {
	mi := &file_circleoftrustmembers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircleOfTrustMembersProto.ProtoReflect.Descriptor instead.
func (*CircleOfTrustMembersProto) Descriptor() ([]byte, []int) {
	return file_circleoftrustmembers_proto_rawDescGZIP(), []int{0}
}

func (x *CircleOfTrustMembersProto) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

var File_circleoftrustmembers_proto protoreflect.FileDescriptor

var file_circleoftrustmembers_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x6f, 0x66, 0x74, 0x72, 0x75, 0x73, 0x74, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61,
	0x69, 0x6e, 0x22, 0x3a, 0x0a, 0x19, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x4f, 0x66, 0x54, 0x72,
	0x75, 0x73, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x73, 0x42, 0x2d,
	0x5a, 0x2b, 0x2e, 0x2f, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x6f, 0x66, 0x74, 0x72, 0x75, 0x73,
	0x74, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x3b, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x6f,
	0x66, 0x74, 0x72, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_circleoftrustmembers_proto_rawDescOnce sync.Once
	file_circleoftrustmembers_proto_rawDescData = file_circleoftrustmembers_proto_rawDesc
)

func file_circleoftrustmembers_proto_rawDescGZIP() []byte {
	file_circleoftrustmembers_proto_rawDescOnce.Do(func() {
		file_circleoftrustmembers_proto_rawDescData = protoimpl.X.CompressGZIP(file_circleoftrustmembers_proto_rawDescData)
	})
	return file_circleoftrustmembers_proto_rawDescData
}

var file_circleoftrustmembers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_circleoftrustmembers_proto_goTypes = []any{
	(*CircleOfTrustMembersProto)(nil), // 0: main.CircleOfTrustMembersProto
}
var file_circleoftrustmembers_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_circleoftrustmembers_proto_init() }
func file_circleoftrustmembers_proto_init() {
	if File_circleoftrustmembers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_circleoftrustmembers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_circleoftrustmembers_proto_goTypes,
		DependencyIndexes: file_circleoftrustmembers_proto_depIdxs,
		MessageInfos:      file_circleoftrustmembers_proto_msgTypes,
	}.Build()
	File_circleoftrustmembers_proto = out.File
	file_circleoftrustmembers_proto_rawDesc = nil
	file_circleoftrustmembers_proto_goTypes = nil
	file_circleoftrustmembers_proto_depIdxs = nil
}
